export const stores = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.770767, 33.01687] },
      properties: {
        phoneFormatted: "(972) 612 1900",
        address: "5508 W Plano Parkway Suite 200",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Advanced Surgical Arts",
        website: "https://www.advsurgicalarts.com",
      },
    },
    // {
    //   type: "Feature",
    //   geometry: { type: "Point", coordinates: [-96.82231095, 32.95041743] },
    //   properties: {
    //     phoneFormatted: "",
    //     address: "5100 Beltline Road #320",
    //     city: "Dallas",
    //     country: "United States",
    //     postalCode: "75254",
    //     state: "TX",
    //     title: "Aesthetic Intelligence",
    //   },
    // },
    // {
    //   type: "Feature",
    //   geometry: { type: "Point", coordinates: [-97.3271504, 32.7454817] },
    //   properties: {
    //     phoneFormatted: "",
    //     address: "201 W. Lancaster Ave #204",
    //     city: "Fort Worth",
    //     country: "United States",
    //     postalCode: "76102",
    //     state: "TX",
    //     title: "Aesthetic Technologies",
    //   },
    // },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.13094327974748, 33.042916464355024],
      },
      properties: {
        phoneFormatted: "(972) 543 2477",
        address: "6020 West Plano Parkway",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "American Institute for Plastic Surgery",
        website: "https://www.ai4ps.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.831122, 33.0158909] },
      properties: {
        phoneFormatted: "(214) 905 5075",
        address: "6405 Hillcrest Ave",
        city: "Flower Mound",
        country: "United States",
        postalCode: "75022",
        state: "TX",
        title: "Aqua Medical Spa",
        website: "https://grandspa.com/partners/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8108577, 33.1285116] },
      properties: {
        phoneFormatted: "(469) 384 2350",
        address: "8501 Wade Blvd Suite #1160",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "ATA Health & Wellness",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8408047, 33.1047325] },
      properties: {
        phoneFormatted: "(469) 213 3750",
        address: "3140 Legacy Drive",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Atomic Beauty Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.10880568264324, 32.93964783676836],
      },
      properties: {
        phoneFormatted: "(817) 749 0155",
        address: "2750 E. Southlake Blvd. Suite #120",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Artemis Laser & Vein Center",
        website: "https://www.atremisrevolution.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7712982, 32.8751442] },
      properties: {
        phoneFormatted: "(214) 506 1115",
        address: "9301 N CENTRAL EXPY STE 470",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Austin & Reddick Dermatology",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.788174, 32.8490662] },
      properties: {
        phoneFormatted: "",
        address: "6825 Snider Plaza",
        city: "University Park",
        country: "United States",
        postalCode: "75205",
        state: "TX",
        title: "Aya Medical Spa & University Park Texas",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77331194553759, 33.05784286372155],
      },
      properties: {
        phoneFormatted: "(972) 519 1600",
        address: "6300 Stonewood Dr., 110",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Bates Wellness",
        website: "",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.80499472333834, 32.86208986270984],
      },
      properties: {
        phoneFormatted: "(469) 585 7211",
        address: "6170 SHERY LANE, #100",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Bella MD - Dr. David Engleman",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.4607083, 32.9144127] },
      properties: {
        phoneFormatted: "",
        address: "1307 Ridge Rd Suite 1104 Room 117",
        city: "Rockwall",
        country: "United States",
        postalCode: "75087",
        state: "TX",
        title: "Beauty Spot Rockwall",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8351361, 33.0328069] },
      properties: {
        phoneFormatted: "(972) 608 0990",
        address: "6213 Chapel Hill Blvd, Suite A",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Beyond Beautiful",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.83083998285169, 33.041499856023584],
      },
      properties: {
        phoneFormatted: "(972) 608 0990",
        address: "3001 Dallas Parkway, Suite D",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Beyond Beautiful: Plastic Surgery and MedSpa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77317602398143, 33.05837648652903],
      },
      properties: {
        phoneFormatted: "(972) 519 1600",
        address: "6300 Stonewood Dr., 110",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "BeWell Medical Spa",
        website: "https://www.bwellmedspa.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.78579973625078, 32.82363559171443],
      },
      properties: {
        phoneFormatted: "(214) 356 5308",
        address: "4633 N Central Expwy #200",
        city: "Dallas",
        country: "United States",
        postalCode: "75007",
        state: "TX",
        title: "Blush Aesthetics & Skincare",
        website: "http://www.blushaestheticsandskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.7719150944554, 32.90988974101031],
      },
      properties: {
        phoneFormatted: "(972) 566 7300",
        address: "7777 Forest Lane Suite B107",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Blush Aesthetics & Skincare",
        website: "http://www.blushaestheticsandskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.81115100622927, 32.861585348014714],
      },
      properties: {
        phoneFormatted: "(214) 739 5600",
        address: "8100 Lomo Alto Dr. Ste. 201",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Blush Aesthetics & Skincare",
        website: "http://www.blushaestheticsandskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.76091751164965, 32.881845455033165],
      },
      properties: {
        phoneFormatted: "(214) 739 5600",
        address: "8230 Walnut Hill La",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Blush Aesthetics & Skincare",
        website: "http://www.blushaestheticsandskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.4207717, 32.8126576] },
      properties: {
        phoneFormatted: "(817) 420 9106",
        address: "3963 Boat Club Rd",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76135",
        state: "TX",
        title: "Boat Club Medical Spa",
        website: "https://www.boatclubmedicalspa.com/?utm_source=gmb_auth",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.70909779, 33.19783014] },
      properties: {
        phoneFormatted: "(945) 888 0180",
        address: "6956 Mediterranean Dr,",
        city: "McKinney",
        country: "United States",
        postalCode: "75071",
        state: "TX",
        title: "Body by Blink",
        website: "http://bodybyblink.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.797299, 33.0823348] },
      properties: {
        phoneFormatted: "(972) 618 2212",
        address: "4800 Hedgcoxe Suite 250",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Brobst Facial Plastic Surgery and Aesthetics",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8369148, 32.8090589] },
      properties: {
        phoneFormatted: "(214) 456 2299",
        address: "1935 Medical District Dr",
        city: "Dallas",
        country: "United States",
        postalCode: "75235",
        state: "TX",
        title: "Children's Medical Center",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7165384, 33.1430933] },
      properties: {
        phoneFormatted: "",
        address: "7850 Collin McKinney Pkwy",
        city: "McKinney",
        country: "United States",
        postalCode: "75070",
        state: "TX",
        title: "Cooper Clinic at Craig Ranch",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1983038, 32.9347104] },
      properties: {
        phoneFormatted: "(972) 392 9393",
        address: "2900 West Southlake Blvd Suite 160",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Corinthian Wellness Spa",
        website: "https://www.corinthianspa.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8658843, 32.819076] },
      properties: {
        phoneFormatted: "(214) 631 5664",
        address: "7929 Brookriver Drive",
        city: "Dallas",
        country: "United States",
        postalCode: "75247",
        state: "TX",
        title: "Cosmetic Procedures Clinic of North Dallas",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.80311656601488, 32.92305299563714],
      },
      properties: {
        phoneFormatted: "(214) 631 5664",
        address: "12800 Preston Rd Ste. 101",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Cosmetic Procedures Clinic of North Dallas",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.86606626715705, 32.819239856415734],
      },
      properties: {
        phoneFormatted: "(214) 631 5664",
        address: "7929 Brookriver Dr Ste. 165",
        city: "Dallas",
        country: "United States",
        postalCode: "75247",
        state: "TX",
        title: "Cosmetic Procedures Clinic of North Dallas",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-98.50743366576992, 33.90235679530709],
      },
      properties: {
        phoneFormatted: "(940) 766 6212",
        address: "1817 10th street",
        city: "Wichita Falls",
        country: "United States",
        postalCode: "76367",
        state: "TX",
        title: "Cosmetic Solutions",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77573539489562, 32.921470099513556],
      },
      properties: {
        phoneFormatted: "(214) 987 3376",
        address: "12700 Park Central Ave, Ste 1210",
        city: "Dallas",
        country: "United States",
        postalCode: "75251",
        state: "TX",
        title: "Dallas Associated Dermatologist",
        website: "https://www.dallasassocderm.com/mary_e_fleischli_md",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7916496, 33.0140611] },
      properties: {
        phoneFormatted: "(469) 800 6000",
        address: "4716 Alliance Blvd #750",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Dallas Diagnostic Assoc. - Baylor Health",
        website: "www.ddadoctors.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7744115, 32.9126714] },
      properties: {
        phoneFormatted: "(972) 566 6000",
        address: "7777 Forest Lane #C303",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Dallas Medical Spa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.93824302398765, 33.022786366505784],
      },
      properties: {
        phoneFormatted: "(972) 566 6000",
        address: "4125 Fairway Drive",
        city: "Carrollton",
        country: "United States",
        postalCode: "75010",
        state: "TX",
        title: "Dallas Medical Spa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7662118, 32.8808555] },
      properties: {
        phoneFormatted: "(301) 919 5235",
        address: "8144 Walnut Hill Lane Ste 901",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Dallas Premier Plastic Surgery P.L.L.C.",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8051576, 32.8929851] },
      properties: {
        phoneFormatted: "(214) 914 1700",
        address: "10707 Preston Rd",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Dauwe Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8051576, 32.8929851] },
      properties: {
        phoneFormatted: "(832) 618 0298",
        address: "66 North Windsail",
        city: "The Woodlands",
        country: "United States",
        postalCode: "77381",
        state: "TX",
        title: "Derm Nuvo - John Murphy, MD",
        website: "http://www.dermnuvo.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.2874341, 32.7382882] },
      properties: {
        phoneFormatted: "",
        address: "101 Sage Suite E",
        city: "Terrell",
        country: "United States",
        postalCode: "75160",
        state: "TX",
        title: "Deja Vu MediSpa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8684053, 32.9156219] },
      properties: {
        phoneFormatted: "",
        address: "9 Medical Parkway Ste. 105",
        city: "Farmers Branch",
        country: "United States",
        postalCode: "75234",
        state: "TX",
        title: "Dermatology Consultants-Dallas",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8081956, 32.862844] },
      properties: {
        phoneFormatted: "(214) 236 2020",
        address: "8222 Douglas Ave. Suite 950",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Dermatology Office, Dr. Ellen Turner",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8081956, 32.862844] },
      properties: {
        phoneFormatted: "(214) 373 7546",
        address: "8222 Douglas Avenue Suite 950",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "DermLaser Institute of Dallas",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.0688778, 33.0442225] },
      properties: {
        phoneFormatted: "",
        address: "2560 Central Park Ave. Suite 200",
        city: "Flower Mound",
        country: "United States",
        postalCode: "75028",
        state: "TX",
        title: "Dr. Drew Sanderson, Flowermound Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7978394, 33.0813729] },
      properties: {
        phoneFormatted: "(469) 406 4245",
        address: "7709 San Jacinto Pl #100",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Dr. Hina Rizvi",
        website: "https://www.drrizviwoundcare.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.4112118, 32.7073608] },
      properties: {
        phoneFormatted: "(817) 870 5080",
        address: "5825 Edwards Ranch Rd Suite #200",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76109",
        state: "TX",
        title: "Dr. Jon Kurkjian Plastic Surgery",
        website: "https://www.jkplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.34418050692473, 32.7364983797107],
      },
      properties: {
        phoneFormatted: "(817) 870 5080",
        address: "800 8th Ave, Suite 336",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76104",
        state: "TX",
        title: "Dr. Jon Kurkjian Plastic Surgery",
        website: "https://www.jkplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7712725, 32.8750274] },
      properties: {
        phoneFormatted: "(214) 389 9797",
        address: "9301 North Central Expressway, 551",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Dr. Ramsey Choucair",
        website: "https://www.southlakeplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.3171726, 32.5863525] },
      properties: {
        phoneFormatted: "",
        address: "11807 South Freeway, Suite 361",
        city: "Burleson",
        country: "United States",
        postalCode: "76028",
        state: "TX",
        title: "Dr. Randy Lew, DPM",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7606896, 32.8816367] },
      properties: {
        phoneFormatted: "(410) 812 2984",
        address: "8230 Walnut Hill Ln Suite 800",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Elevate Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.8146280961971, 32.81949600471242],
      },
      properties: {
        phoneFormatted: "(803) 795 3710",
        address: "4525 Lemmon Ave",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Elevate Med Spa - Dr. Thornwell Parker",
        website:
          "https://elevatemedicalspa.com/procedures?ispublished=1#coolsculpting",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.2920538, 32.9143378] },
      properties: {
        phoneFormatted: "(817) 306 9494",
        address: "4400 Heritage Trace Parkway, Suite 204",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76244",
        state: "TX",
        title: "Elite Health Center - Michael Bailey, MD",
        website: "http://www.alliancemedspas.com/index.html",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.31406629580096, 32.90507640721898],
      },
      properties: {
        phoneFormatted: "(817) 306 9494",
        address: "9140 North Freeway",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76177",
        state: "TX",
        title: "Elite Health Center - Michael Bailey, MD",
        website: "http://www.alliancemedspas.com/index.html",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7712352, 32.8724069] },
      properties: {
        phoneFormatted: "(214) 887 1577",
        address: "9101 N. Central Expy. Suite 500",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "EpiCentre Skin Care & Laser Center",
        website: "https://epicentreskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.811241, 33.0630758] },
      properties: {
        phoneFormatted: "",
        address: "5425 W. Spring Creek Parkway",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Erase",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.4148809, 32.7294606] },
      properties: {
        phoneFormatted: "(817) 731 0707",
        address: "6038 Camp Bowie Blvd",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76116",
        state: "TX",
        title: "European Skincare & Med Spa",
        website: "https://www.euroskincare.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.11320083781521, 32.93800044746943],
      },
      properties: {
        phoneFormatted: "(817) 305 0050",
        address: "2485 E. Southlake Blvd #200",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Fawad Ghafoori, MD",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7665636, 32.8793388] },
      properties: {
        phoneFormatted: "",
        address: "8140 Walnut Hill Lane Suite 601",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Facial Techniques",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8111108, 33.1287324] },
      properties: {
        phoneFormatted: "(214) 733 6969",
        address: "8501 Wade Boulevard",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Fine Line Aesthetics",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.07241026736375, 33.0253865832426],
      },
      properties: {
        phoneFormatted: "(972) 691 7900",
        address: "2931 Long Prairie Rd Suite 100",
        city: "Flower Mound",
        country: "United States",
        postalCode: "75022",
        state: "TX",
        title: "Flower Mound Center for Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.06887779981405, 33.04423145523651],
      },
      properties: {
        phoneFormatted: "(972) 691 7900",
        address: "2560 Central Park Avenue #200",
        city: "Flower Mound",
        country: "United States",
        postalCode: "75028",
        state: "TX",
        title: "Flower Mound Center for Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8387221, 33.1507648] },
      properties: {
        phoneFormatted: "",
        address: "5500 Frisco Square Blvd",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Forest Park Medical Center - Frisco",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8221204, 32.927956] },
      properties: {
        phoneFormatted: "(214) 540 0371",
        address: "5005 LBJ Fwy #107",
        city: "Dallas",
        country: "United States",
        postalCode: "75244",
        state: "TX",
        title: "Fresh Image Cosmetic Surgery Center",
        website: "https://www.FreshImageCenter.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.82890626781429, 32.9870400511191],
      },
      properties: {
        phoneFormatted: "(214) 540 0371",
        address: "17311 Dallas Parkway St 100",
        city: "Dallas",
        country: "United States",
        postalCode: "75248",
        state: "TX",
        title: "Fresh Image Cosmetic Surgery Center",
        website: "https://www.FreshImageCenter.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.82573564, 33.12495774] },
      properties: {
        phoneFormatted: "",
        address: "6898 Lebanon Road",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Frisco Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.773254, 32.910057] },
      properties: {
        phoneFormatted: "(800) 425 2139",
        address: "7777 Forest Ln Ste C717",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Genecov Plastic Surgery Group PA",
        website: "https://www.genecovplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.773254, 32.910057] },
      properties: {
        phoneFormatted: "(972) 331 1910",
        address: "11970 N Central Expy #270",
        city: "Dallas",
        country: "United States",
        postalCode: "75240",
        state: "TX",
        title: "Genecov Plastic Surgery Group PA",
        website: "https://www.genecovplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.4645384, 32.7554618] },
      properties: {
        phoneFormatted: "",
        address: "108 E US Hwy 80, Suite 150",
        city: "Forney",
        country: "United States",
        postalCode: "75126",
        state: "TX",
        title: "Genesis Wellness & Pain",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8000014, 32.8662491] },
      properties: {
        phoneFormatted: "",
        address: "6211 W. Northwest Hwy., Suite C255",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "GOH Medical Spa - Scott Conard, MD",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.820664, 32.9513587] },
      properties: {
        phoneFormatted: "(717) 645 1635",
        address: "5100 Belt Line, STE 620",
        city: "Dallas",
        country: "United States",
        postalCode: "75254",
        state: "TX",
        title: "Grand Spa",
        website: "https://grandspa.com/partners/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.84502326917732, 32.81697021107985],
      },
      properties: {
        phoneFormatted: "(214) 905 5075",
        address: "5939 Harry Hines Suite 739",
        city: "Dallas",
        country: "United States",
        postalCode: "75235",
        state: "TX",
        title: "Grand Spa",
        website: "https://grandspa.com/partners/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7612476, 32.8818916] },
      properties: {
        phoneFormatted: "(214) 707 2497",
        address: "8220 Walnut Hill Lane, Building 2, Suite 108",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Gregg Anigian, MD",
        website: "https://www.dallasplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.2891656, 32.9163856] },
      properties: {
        phoneFormatted: "",
        address: "9734 North Beach Street #100",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76244",
        state: "TX",
        title: "Hidden Door Med Spa Fort Worth",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1303591, 32.9430433] },
      properties: {
        phoneFormatted: "(817) 488 8848",
        address: "1422 Main st #263",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Hidden Door Medspa at Southlake Town Square",
        website: "https://www.hiddendoorspa.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1143198, 32.6830907] },
      properties: {
        phoneFormatted: "",
        address: "3751 Matlock Road Suite 113",
        city: "Arlington",
        country: "United States",
        postalCode: "76015",
        state: "TX",
        title: "Ideal Image - Arlington",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.14806, 32.892951] },
      properties: {
        phoneFormatted: "",
        address: "5712 Colleyville Blvd Suite 140",
        city: "Colleyville",
        country: "United States",
        postalCode: "76034",
        state: "TX",
        title: "Ideal Image - Colleyville",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.6153228, 32.9574111] },
      properties: {
        phoneFormatted: "",
        address: "4430 Lavon Drive Suite 364",
        city: "Garland",
        country: "United States",
        postalCode: "75040",
        state: "TX",
        title: "Ideal Image - Garland",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8042464, 33.0956049] },
      properties: {
        phoneFormatted: "",
        address: "8612 Preston Road Suite 100",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Ideal Image - Plano",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7965091, 32.8097457] },
      properties: {
        phoneFormatted: "",
        address: "3839 McKinney Ave Suite 100",
        city: "Dallas",
        country: "United States",
        postalCode: "75204",
        state: "TX",
        title: "Ideal Image - West Village",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.3992737, 32.6752918] },
      properties: {
        phoneFormatted: "",
        address: "5000 South Hulen St Suite 116",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76132",
        state: "TX",
        title: "Ideal Image - Fort Worth",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1416798, 32.5641817] },
      properties: {
        phoneFormatted: "(817) 584 3710",
        address: "800 8th Ave Ste 200",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76104",
        state: "TX",
        title: "In2ition Medical Aesthetics",
        website: "https://www.in2itionmedicalaesthetics.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.337225, 32.7446667] },
      properties: {
        phoneFormatted: "",
        address: "1401 Henderson St.",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76102",
        state: "TX",
        title: "Institute of Age Management & Aesthetic Medicine",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7744115, 32.9126714] },
      properties: {
        phoneFormatted: "(214) 708 6961",
        address: "7777 Forest Lane C230",
        city: "Plano",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "John Antonetti",
        website: "https://www.cliniquedallas.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.4664362, 32.8996027] },
      properties: {
        phoneFormatted: "",
        address: "2455 Ridge Road Suite 157",
        city: "Rockwall",
        country: "United States",
        postalCode: "75087",
        state: "TX",
        title: "Juvanew Medspa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8145455, 32.8192494] },
      properties: {
        phoneFormatted: "",
        address: "4525 Lemmon Ave",
        city: "Dallas",
        country: "United States",
        postalCode: "75219",
        state: "TX",
        title: "Kevin Hanz, MD.",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8408579, 33.10448] },
      properties: {
        phoneFormatted: "(972) 469 2626",
        address: "3140 Legacy Dr Suite 110",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Legacy Dermatology - Frisco",
        website: "https://www.legacydermatology.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8019238, 32.9886236] },
      properties: {
        phoneFormatted: "(214) 924 6641",
        address: "17370 Preston Rd ste 412",
        city: "Dallas",
        country: "United States",
        postalCode: "75252",
        state: "TX",
        title: "Lily Med Spa",
        website: "https://www.lilymedspa.com/Index.aspx",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.79872189940941, 32.95505414489718],
      },
      properties: {
        phoneFormatted: "(214) 212 6419",
        address: "6235 Liberty Hill",
        city: "Dallas",
        country: "United States",
        postalCode: "75223",
        state: "TX",
        title: "Lily Med Spa",
        website: "https://www.lilymedspa.com/Index.aspx",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.80253563939557, 32.9518580989452],
      },
      properties: {
        phoneFormatted: "(214) 212 6419",
        address: "14902 Preston Rd, Suite 506",
        city: "Dallas",
        country: "United States",
        postalCode: "75252",
        state: "TX",
        title: "Lily Med Spa",
        website: "https://www.lilymedspa.com/Index.aspx",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.74353096734883, 32.804124642308096],
      },
      properties: {
        phoneFormatted: "(214) 212 6419",
        address: "626 Cordova Street",
        city: "Dallas",
        country: "United States",
        postalCode: "75223",
        state: "TX",
        title: "Lily Med Spa",
        website: "https://www.lilymedspa.com/Index.aspx",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7508566, 32.8980598] },
      properties: {
        phoneFormatted: "(214) 221 9222",
        address: "8722 Greenville Ave Suite 101",
        city: "Dallas",
        country: "United States",
        postalCode: "75243",
        state: "TX",
        title: "Lonnie Whiddon, MD",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7965027, 32.8038901] },
      properties: {
        phoneFormatted: "(214) 763 1111",
        address: "2801 Lemmon Ave #300",
        city: "Dallas",
        country: "United States",
        postalCode: "75204",
        state: "TX",
        title: "Mark Deuber MD",
        website: "https://www.drdeuber.com/face/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.830494, 33.0646382] },
      properties: {
        phoneFormatted: "(972) 316 4555",
        address: "6000 W Spring Creek Parkway Suite 200",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "McGuiness Dermatology",
        website: "https://www.mcguinessdermatology.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.3078451, 32.5816178] },
      properties: {
        phoneFormatted: "(817) 718 1383",
        address: "701 East Rendon Crowley Road",
        city: "Burleson",
        country: "United States",
        postalCode: "76028",
        state: "TX",
        title: "Med Spa at Seena One",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77395428095262, 33.08728952876564],
      },
      properties: {
        phoneFormatted: "(972) 467 1006",
        address: "4032 Carmichael Dr",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Med Spa Studios",
        website: "https://www.medspastudios.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.75262409350903, 33.10060994374171],
      },
      properties: {
        phoneFormatted: "(214) 619 5000",
        address: "3109 Rocky Mountain Dr",
        city: "Plano",
        country: "United States",
        postalCode: "75025",
        state: "TX",
        title: "Med Spa Studios",
        website: "https://www.medspastudios.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7915582, 33.0140835] },
      properties: {
        phoneFormatted: "(214) 577 1777",
        address: "Baylor Regional Medical Center Pavillion Two",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Medical Aesthetics of North Dallas",
        website: "https://www.northdallasmedspa.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.9852588, 32.8928397] },
      properties: {
        phoneFormatted: "",
        address: "2448 Gateway Dr. Ste 150",
        city: "Irving",
        country: "United States",
        postalCode: "75063",
        state: "TX",
        title: "Medical Alliance, Inc",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7744115, 32.9126714] },
      properties: {
        phoneFormatted: "",
        address: "7777 Forest Ln",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Medical City Children's Hospital",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8631823, 33.1537468] },
      properties: {
        phoneFormatted: "",
        address: "3110 W. Main Street Suite 150",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "MediLaser - Mauricio Giraldo, MD",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.3988785, 32.7098204] },
      properties: {
        phoneFormatted: "(682) 235 2325",
        address: "5160 Marathon Avenue",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76109",
        state: "TX",
        title: "Milk + Honey Fort Worth",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7711941, 32.8723873] },
      properties: {
        phoneFormatted: "(214) 265 1818",
        address: "9101 N. Central Expressway Ste 150",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Modern Dermatology",
        website: "bswhealth.org",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7668158, 32.9122369] },
      properties: {
        phoneFormatted: "",
        address: "11970 N Central Expy #270",
        city: "Dallas",
        country: "United States",
        postalCode: "75243",
        state: "TX",
        title: "Modern Medical Spa",
        website: "https://www.modernmedicalspa.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8512651, 32.8611427] },
      properties: {
        phoneFormatted: "(469) 338 1417",
        address: "3850 W NW Highway Suite 1100",
        city: "Dallas",
        country: "United States",
        postalCode: "75220",
        state: "TX",
        title: "National Laser Institute - Texas",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8053675, 32.8938067] },
      properties: {
        phoneFormatted: "(214) 216 6364",
        address: "5952 ROYAL LANE SUITE 120",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "NeoGenesis Anti Aging Center Dallas",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8048141, 32.8627605] },
      properties: {
        phoneFormatted: "",
        address: "8201 Preston Road, Suite 540",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Neu Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.83689634450029, 33.15313968379847],
      },
      properties: {
        phoneFormatted: "(214) 557 2449",
        address: "5858 Main Street Suite 210",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Oceanview Medical Spa",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.79013667882786, 33.022048817217545],
      },
      properties: {
        phoneFormatted: "(817) 368 9838",
        address: "4701 Old Shepard Dr., Suite 260",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Optimal Health & Skin",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8013608, 32.8159746] },
      properties: {
        phoneFormatted: "(770) 504 6000",
        address: "3888 Oak Lawn Avenue",
        city: "Dallas",
        country: "United States",
        postalCode: "75219",
        state: "TX",
        title: "OVME Aesthetics",
        website: "https://www.ovme.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-84.37576428014417, 33.851910868985414],
      },
      properties: {
        phoneFormatted: "(770) 504 6000",
        address: "3495 Piedmont Rd NE, Building 11, Suite 710",
        city: "Atlanta",
        country: "United States",
        postalCode: "30305",
        state: "TX",
        title: "OVME Aesthetics",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8080492, 32.8633169] },
      properties: {
        phoneFormatted: "",
        address: "8226 Douglas Ave. Ste. 540",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Park Cities Dermatology",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8352201, 32.8142564] },
      properties: {
        phoneFormatted: "",
        address: "5223 Tex Oak Ave.",
        city: "Dallas",
        country: "United States",
        postalCode: "75235",
        state: "TX",
        title: "Parkland Hospital",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.799934482437, 32.9240170908292],
      },
      properties: {
        phoneFormatted: "(972) 661 5077",
        address: "6190 LBJ Freeway, Suite 500",
        city: "Dallas",
        country: "United States",
        postalCode: "75240",
        state: "TX",
        title: "Plastic Surgery Center of Dallas",
        website: "https://www.cosmeticsurgerydallas.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77621714898773, 32.92154994892423],
      },
      properties: {
        phoneFormatted: "(214) 751 2374",
        address: "12700 Park Central Dr",
        city: "Plano",
        country: "United States",
        postalCode: "75025",
        state: "TX",
        title: "Platinum Dermatology",
        website: "https://www.platinumdermatology.com.au/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7717161, 33.0168592] },
      properties: {
        phoneFormatted: "(972) 398 1131",
        address: "4104 W. 15th St. Ste 200",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Premier Plastic Surgery of Texas",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.19826575369197, 32.934770416975454],
      },
      properties: {
        phoneFormatted: "(817) 379 9397",
        address: "2900 W Southlake Blvd Suite 160",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Refine Medspa",
        website: "https://www.refine-medspa.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8082147, 32.8633178] },
      properties: {
        phoneFormatted: "(219) 754 6865",
        address: "8226 Douglas Suite #104",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Resurrect Skin M.D.",
        website: "https://www.resurrectskinmd.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8047688, 32.8627241] },
      properties: {
        phoneFormatted: "(214) 675 3227",
        address: "8201 Preston Rd #440",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Revival Dermatology",
        website: "https://www.revivalderm.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7731653, 33.0581787] },
      properties: {
        phoneFormatted: "",
        address: "6300 Stonewood Dr. 110",
        city: "Plano",
        country: "United States",
        postalCode: "75024",
        state: "TX",
        title: "Rosemary Bates MD",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.13458431, 32.95018806] },
      properties: {
        phoneFormatted: "",
        address: "750 N Carroll Ave",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Sedo Laser",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8277048, 32.99669585] },
      properties: {
        phoneFormatted: "",
        address: "18170 Dallas Pkwy",
        city: "Dallas",
        country: "United States",
        postalCode: "75287",
        state: "TX",
        title: "Setty Plastic Surgery",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.0577847, 33.0332999] },
      properties: {
        phoneFormatted: "(214) 738 7304",
        address: "3535 Firewheel A-112",
        city: "Flower Mound",
        country: "United States",
        postalCode: "75067",
        state: "TX",
        title: "Simply Embellish",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.79556611476644, 33.03102386131948],
      },
      properties: {
        phoneFormatted: "(214) 738 7304",
        address: "2401 Preston Rd Suite F",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Skin Spirit - Plano",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.804373, 32.8063347] },
      properties: {
        phoneFormatted: "(469) 829 4200",
        address: "3131 Turtle Creek Boulevard Suite 600",
        city: "Dallas",
        country: "United States",
        postalCode: "75219",
        state: "TX",
        title: "Skin Pharm - Dallas/Turtle Creek",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7606896, 32.8816367] },
      properties: {
        phoneFormatted: "(214) 696 8828",
        address: "8230 Walnut Hill Ln Suite 808",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Skincepts Medical Skincare",
        website: "https://www.skincepts.com/home",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8476218, 33.1578975] },
      properties: {
        phoneFormatted: "(318) 560 2366",
        address: "9560 Legacy Suite 200",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Skinn Bar",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-98.21912917675314, 26.264906378615816],
      },
      properties: {
        phoneFormatted: "(318) 560 2366",
        address: "7000 N 10th St Suite C-1",
        city: "McAllen",
        country: "United States",
        postalCode: "78504",
        state: "TX",
        title: "Skinn Bar",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.83280227, 33.05475206] },
      properties: {
        phoneFormatted: "",
        address: "6100 Windhaven Parkway",
        city: "Plano",
        country: "United States",
        postalCode: "75093",
        state: "TX",
        title: "Skinnovations",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7744115, 32.9126714] },
      properties: {
        phoneFormatted: "",
        address: "7777 Forest Ln, Ste B-410",
        city: "Dallas",
        country: "United States",
        postalCode: "75230",
        state: "TX",
        title: "Skyn Lab Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8097713, 33.1051014] },
      properties: {
        phoneFormatted: "(972) 596 7227",
        address: "8600 Gaylord Parkway Suite 1",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Sonoma Skin Works",
        website: "https://www.sonomaskinworks.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1375551, 32.941649] },
      properties: {
        phoneFormatted: "(817) 442 0810",
        address: "900 E. Southlake Boulevard Suite 100",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Southlake Plastic Surgery",
        website: "https://www.southlakeplasticsurgery.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.82550620175104, 33.12365719921798],
      },
      properties: {
        phoneFormatted: "(214) 705 0400",
        address: "6950 Lebanon Rd #105",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Starwood Med Spa",
        website: "https://www.starwoodmedspa.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.15183741741431, 32.96016196112757],
      },
      properties: {
        phoneFormatted: "(817) 912 1200",
        address: "245 W State Highway 114, Ste 100",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "Stay Ageless Aesthetic Specialists",
        website: "https://www.stayageless.com/",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.36699419580894, 32.73111911410341],
      },
      properties: {
        phoneFormatted: "",
        address: "3416 Lovell Avenue Suite 200",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76107",
        state: "TX",
        title: "Steven Camp MD Plastic Surgery",
        website: "https://www.campplasticsurgery.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.0585357, 33.0722492] },
      properties: {
        phoneFormatted: "(972) 333 0321",
        address: "2300 Highland Village Road , Suite 300",
        city: "Highland Villag",
        country: "United States",
        postalCode: "75077",
        state: "TX",
        title: "Studio 360 Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8028626, 32.8209778] },
      properties: {
        phoneFormatted: "(214) 821 9355",
        address: "4311 Oak Lawn #380",
        city: "Dallas",
        country: "United States",
        postalCode: "75219",
        state: "TX",
        title: "Surface Clinical",
        website: "https://www.surfaceclinical.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.77128195721188, 32.872386639222384],
      },
      properties: {
        phoneFormatted: "(214) 540 1416",
        address: "9101 N Central Expy Ste 600",
        city: "Dallas",
        country: "United States",
        postalCode: "75231",
        state: "TX",
        title: "Surface Clinical",
        website: "https://www.surfaceclinical.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.4664624, 32.8852928] },
      properties: {
        phoneFormatted: "",
        address: "3142 Horizon Road, Suite 201",
        city: "Rockwall",
        country: "United States",
        postalCode: "75032",
        state: "TX",
        title: "Texas Dermatology & Skin Cancer Center",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7770034, 32.7912842] },
      properties: {
        phoneFormatted: "",
        address: "3900 Junius St Suite 145",
        city: "Dallas",
        country: "United States",
        postalCode: "75246",
        state: "TX",
        title: "Texas Dermatology Associates",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8387851, 33.105148] },
      properties: {
        phoneFormatted: "",
        address: "5575 Warren Parkway Suite 314 Prof Bldg 1",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Texas Gynecology",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7253113, 32.9745103] },
      properties: {
        phoneFormatted: "",
        address: "399 W. Campbell Rd Medical Bldg 2 Ste 412",
        city: "Richardson",
        country: "United States",
        postalCode: "75080",
        state: "TX",
        title: "The Finer Touch",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-97.12254382216489, 32.94575748498484],
      },
      properties: {
        phoneFormatted: "(817) 251 1000",
        address: "1910 E State Hwy 114",
        city: "Southlake",
        country: "United States",
        postalCode: "76092",
        state: "TX",
        title: "The LAB MedSpa",
        website: "https://www.thelabmedspa.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8837356, 33.0275908] },
      properties: {
        phoneFormatted: "(972) 492 7900",
        address: "4340 N Josey Ln #100",
        city: "Carrollton",
        country: "United States",
        postalCode: "75010",
        state: "TX",
        title: "Trinity Dermatology",
        website: "https://www.trinitydermatology.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.344213, 32.736237] },
      properties: {
        phoneFormatted: "",
        address: "800 8th Ave., Suite 326",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76104",
        state: "TX",
        title: "Trinity Vista Dermatology",
        website: "https://www.trinitydermatology.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7893117, 32.8139484] },
      properties: {
        phoneFormatted: "(214) 303 1102",
        address: "4144 North Central Expressway; Suite 855",
        city: "Dallas",
        country: "United States",
        postalCode: "75204",
        state: "TX",
        title: "Uptown Derm - Farhad Niroomand, M.D., P.A.",
        website: "http://www.uptownderm.com",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1299772, 32.7438366] },
      properties: {
        phoneFormatted: "",
        address: "723 N Fielder Rd Ste B",
        city: "Arlington",
        country: "United States",
        postalCode: "76012",
        state: "TX",
        title: "US Dermatology Medical Group",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8458178, 32.816098] },
      properties: {
        phoneFormatted: "(214) 645 3150",
        address: "1801 Inwood Rd 5th Floor",
        city: "Dallas",
        country: "United States",
        postalCode: "75390",
        state: "TX",
        title:
          "UT Southwestern Medical Center-Plastic Surgery - Jeffrey Kenkel, MD",
        website:
          "https://www.utswmed.org/conditions-treatments/plastic-surgery/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8485427, 32.8195873] },
      properties: {
        phoneFormatted: "",
        address: "6263 Harry Hines Blvd. 4th Floor, Room 120",
        city: "Dallas",
        country: "United States",
        postalCode: "75390",
        state: "TX",
        title: "UT Southwestern Medical - Dermatology",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8463936, 32.8158484] },
      properties: {
        phoneFormatted: "",
        address: "1801 Inwood Rd",
        city: "Dallas",
        country: "United States",
        postalCode: "75390",
        state: "TX",
        title: "UTSW",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7691595, 32.8604732] },
      properties: {
        phoneFormatted: "",
        address: "8080 N. Central Express Way Suite 1250",
        city: "Dallas",
        country: "United States",
        postalCode: "75206",
        state: "TX",
        title: "Vansanity - Dallas",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8067158, 33.1014628] },
      properties: {
        phoneFormatted: "",
        address: "2693 Preston Rd. - 1080 / #40",
        city: "Frisco",
        country: "United States",
        postalCode: "75034",
        state: "TX",
        title: "Vibrant Skincare and Laser Center, LLC",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.7945503, 33.0058879] },
      properties: {
        phoneFormatted: "",
        address: "18800 Preston Rd, Ste 310",
        city: "Dallas",
        country: "United States",
        postalCode: "75252",
        state: "TX",
        title: "Vital Wellness and Weight Loss",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8045541, 32.8498138] },
      properties: {
        phoneFormatted: "(210) 386 3152",
        address: "6915 Preston Rd",
        city: "Dallas",
        country: "United States",
        postalCode: "75205",
        state: "TX",
        title: "Vitalyc Medspa",
        website: "https://www.vitalycmedspa.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.69669884160436, 33.198109966037215],
      },
      properties: {
        phoneFormatted: "",
        address: "5913 Virginia Pkwy #100",
        city: "McKinney",
        country: "United States",
        postalCode: "75070",
        state: "TX",
        title: "Warthan Dermatology",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.8048141, 32.8627605] },
      properties: {
        phoneFormatted: "",
        address: "8201 Preston Rd. #540",
        city: "Dallas",
        country: "United States",
        postalCode: "75225",
        state: "TX",
        title: "Wellskin Med Spa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.3379423, 32.7308068] },
      properties: {
        phoneFormatted: "(817) 870 4833",
        address: "1200 W. Magnolia Ave Suite 110",
        city: "Fort Worth",
        country: "United States",
        postalCode: "76104",
        state: "TX",
        title: "West Magnolia Plastic Surgery",
        website: "http://www.mclaughlinmd.com",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-96.82779568488506, 32.98276450565022],
      },
      properties: {
        phoneFormatted: "(972) 372 9313",
        address: "17110 Dallas Pkwy Suite 100",
        city: "Plano",
        country: "United States",
        postalCode: "75248",
        state: "TX",
        title: "Wilcox Robert D. MD",
        website: "https://www.drwilcox.com/",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-96.6832138, 33.089836] },
      properties: {
        phoneFormatted: "(214) 551 2287",
        address: "941 West Bethany Dr",
        city: "Allen",
        country: "United States",
        postalCode: "75013",
        state: "TX",
        title: "Youthful Infusion",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.219731, 33.0132604] },
      properties: {
        phoneFormatted: "",
        address: "1212 N Hwy 377 Suite 119",
        city: "Roanoke",
        country: "United States",
        postalCode: "76262",
        state: "TX",
        title: "Youthology MedSpa",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-97.1053589, 32.9435107] },
      properties: {
        phoneFormatted: "(817) 442 1236",
        address: "2301 Westgate Plaza",
        city: "Grapevine",
        country: "United States",
        postalCode: "76051",
        state: "TX",
        title: "2301 Plastic Surgery",
        website: "",
      },
    },
  ],
};
